SELECT * FROM PLAYER;

ROLLBACK;

UPDATE PLAYER 
SET PLAYER_NAME = '허은상'
WHERE TEAM_ID  = 'K01';

DELETE FROM PLAYER p 
WHERE "POSITION" = 'MF';

DELETE FROM PLAYER p 
WHERE HEIGHT >=180;

SELECT * FROM PLAYER p WHERE "POSITION"  IS NULL;

SELECT  BACK_NO  "등 번호" , NICKNAME " 선수 별명" FROM PLAYER p 

SELECT PLAYER_NAME  || '님의 영어 이름은' || E_PLAYER_NAME 자기소개 FROM PLAYER p ;

SELECT PLAYER_NAME  || '의 POSITION 은 '  || "POSITION" ||'이다' 포지션소개 FROM PLAYER p 

SELECT * FROM TEAM t 
WHERE TEAM_NAME LIKE '%천마';


SELECT * FROM PLAYER p 
WHERE PLAYER_NAME LIKE '김%';

SELECT * FROM PLAYER p 
WHERE PLAYER_NAME LIKE'김_';

SELECT * FROM PLAYER p 
WHERE PLAYER_NAME  LIKE '김%' OR PLAYER_NAME LIKE '이%';



SELECT * FROM PLAYER p 
WHERE PLAYER_NAME NOT LIKE '김%';

/*
 * 집계 함수 : 결과 행 1개 
 *
 *NULL은 포함시키지 않는다, WHERE절에서 사용 불가
 *
 *
 *
 */

SELECT "POSITION"  FROM PLAYER 
WHERE WEIGHT >=80 
GROUP BY "POSITION"  
HAVING AVG(HEIGHT)>=180;
 

SELECT JOB_ID, AVG(SALARY)  FROM EMPLOYEES 
GROUP BY JOB_ID 
HAVING AVG(SALARY)<10000
ORDER BY AVG(SALARY ) ; 

SELECT AVG(HEIGHT), (SELECT AVG(HEIGHT) FROM PLAYER ) FROM PLAYER p 
GROUP BY "POSITION" ;


SELECT * FROM (SELECT * FROM PLAYER WHERE TEAM_ID = 'K01')
WHERE "POSITION" = 'GK';

SELECT * FROM PLAYER p ;

SELECT * FROM PLAYER 
WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM PLAYER );

SELECT AVG(WEIGHT) FROM PLAYER ;


SELECT * FROM PLAYER p 
WHERE TEAM_ID = (SELECT TEAM_ID FROM PLAYER WHERE PLAYER_NAME = '정남일');

SELECT PLAYER_NAME ,HEIGHT , MAX(HEIGHT) OVER () FROM PLAYER p 
WHERE HEIGHT <(SELECT AVG(HEIGHT) FROM PLAYER);


SELECT * FROM STADIUM 
WHERE STADIUM_ID 
IN
(SELECT STADIUM_ID FROM SCHEDULE S
WHERE TO_NUMBER(SCHE_DATE)  BETWEEN 20120501 AND 20120502);

SELECT STADIUM_ID,SCHE_DATE  FROM SCHEDULE S
WHERE TO_NUMBER(SCHE_DATE)  BETWEEN 20120501 AND 20120502;


UPDATE PLAYER 
SET NICKNAME = (SELECT NICKNAME FROM PLAYER WHERE PLAYER_NAME = '정태민')
WHERE NICKNAME IS NULL;

SELECT * FROM PLAYER p ;
SELECT * FROM EMPLOYEES e;

UPDATE EMPLOYEES 
SET SALARY = 1.2*SALARY 
WHERE SALARY <(SELECT AVG(SALARY) FROM EMPLOYEES e);

DELETE FROM PLAYER p 
WHERE HEIGHT > (SELECT AVG(HEIGHT) FROM PLAYER);


