CREATE SEQUENCE SEQ_ANIMAL;
CREATE SEQUENCE SEQ_STUDENT;

DROP SEQUENCE SEQ_ANIMAL ;

SELECT * FROM TBL_ANIMAL ;

INSERT INTO HR.TBL_ANIMAL
(ANIMAL_ID, ANIMAL_KIND, ANIMAL_FEED, ANIMAL_AGE)
VALUES(SEQ_ANIMAL.NEXTVAL, '고양이', '사료', 10);

UPDATE TBL_ANIMAL 
SET ANIMAL_KIND ='고양이'
WHERE ANIMAL_KIND = '개';

DELETE FROM TBL_ANIMAL;



INSERT INTO TBL_STUDENT
(STUDENT_ID, STUDENT_IDENTIFICATION, STUDENT_NAME, STUDENT_MAJOR, STUDENT_GENDER, STUDENT_BIRTH, STUDENT_AGE, STUDENT_GRADE)
VALUES(SEQ_STUDENT.NEXTVAL , 'HES', '허은상', '컴퓨터', 'M', '2000-01-03', 23, 'A');




SELECT * FROM TBL_STUDENT ;

SELECT * FROM TBL_FLOWER;

SELECT * FROM TBL_POT ;

DROP TABLE TBL_PET ;
DROP TABLE TBL_OWNER ;


CREATE TABLE TBL_OWNER(
   OWNER_ID NUMBER CONSTRAINT PK_OWNER PRIMARY KEY,
   OWNER_NAME VARCHAR2(500) NOT NULL,
   OWNER_AGE NUMBER,
   OWNER_ADDRESS VARCHAR2(500) NOT NULL,
   OWNER_PHONE VARCHAR2(500) NOT NULL
);


CREATE TABLE TBL_PET(
   PET_ID NUMBER CONSTRAINT PK_PET PRIMARY KEY,
   PET_TYPE VARCHAR2(500) NOT NULL,
   PET_NAME VARCHAR2(500) NOT NULL,
   PET_AGE NUMBER NOT NULL,
   PET_ILL_NAME VARCHAR2(500) NOT NULL,
   OWNER_ID NUMBER,
   CONSTRAINT FK_PET_OWNER FOREIGN KEY(OWNER_ID)
   REFERENCES TBL_OWNER(OWNER_ID)
);

CREATE SEQUENCE SEQ_PET;
CREATE SEQUENCE SEQ_OWNER;


INSERT INTO TBL_OWNER
(OWNER_ID, OWNER_NAME, OWNER_ADDRESS, OWNER_PHONE, OWNER_AGE)
VALUES(SEQ_OWNER.NEXTVAL , '홍윤기', '인천광역시 부평', '010-4143-1234', 22);

SELECT * FROM TBL_PET ;
SELECT * FROM TBL_OWNER ;

INSERT INTO TBL_PET
(PET_ID, PET_NAME, PET_TYPE, PET_AGE , PET_ILL_NAME, OWNER_ID)
VALUES(SEQ_PET.NEXTVAL  , '공주', '고양이', 10, '관절염',4);




SELECT OWNER_ID FROM TBL_PET GROUP BY OWNER_ID HAVING COUNT(OWNER_ID) >=2;

SELECT COUNT(OWNER_ID) FROM TBL_PET GROUP BY OWNER_ID;

UPDATE TBL_OWNER 
SET OWNER_PHONE  = '010-4284-8234'
WHERE OWNER_ID =(SELECT OWNER_ID FROM TBL_PET GROUP BY OWNER_ID HAVING COUNT(OWNER_ID) >=2);




SELECT * FROM PLAYER p 

SELECT * FROM PLAYER p 
WHERE TEAM_ID = 'K01';


SELECT * FROM PLAYER p 
WHERE TEAM_ID !='K01';

SELECT * FROM PLAYER p 
WHERE WEIGHT >=70 AND WEIGHT <=80;

SELECT * FROM PLAYER p 
WHERE TEAM_ID ='K03' AND HEIGHT <180;

SELECT * FROM PLAYER p 
WHERE TEAM_ID ='K06' AND NICKNAME ='제리';

SELECT PLAYER_NAME  FROM PLAYER p 
WHERE HEIGHT >=170 AND WEIGHT >=80;

SELECT * FROM STADIUM s 
WHERE SEAT_COUNT >30000 AND SEAT_COUNT <=41000;

SELECT * FROM PLAYER p 
WHERE TEAM_ID IN('K01','K07') AND "POSITION" ='MF';




SELECT * FROM player;

SELECT * FROM EMPLOYEES e ;

