SELECT E.ENAME , D.LOC FROM 
EMP E JOIN DEPT d 
ON E.DEPTNO = D.DEPTNO ;

SELECT TEL FROM PLAYER p NATURAL JOIN TEAM t 
WHERE P.PLAYER_NAME = '송종국';


SELECT TEL FROM PLAYER P INNER JOIN TEAM T 
USING(TEAM_ID)
WHERE P.PLAYER_NAME = '송종국';

SELECT TEL FROM PLAYER P INNER JOIN TEAM T 
ON T.TEAM_ID = P.TEAM_ID AND P.PLAYER_NAME = '송종국';



SELECT j.JOB_TITLE , e.EMAIL , e.FIRST_NAME ,e.LAST_NAME 
FROM EMPLOYEES e INNER JOIN JOBS j ON e.JOB_ID = j.JOB_ID ;

SELECT  SAL,GRADE
FROM SALGRADE s JOIN EMP e 
ON e.SAL BETWEEN s.LOSAL AND s.HISAL  ;

SELECT  e.EMPLOYEE_ID ,e.FIRST_NAME,e.LAST_NAME ,d.DEPARTMENT_NAME 
FROM EMPLOYEES e JOIN DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID AND TO_CHAR(e.HIRE_DATE,'YYYY')  BETWEEN '2003' AND '2005';

SELECT  AVG(E.SALARY) ,JOB_TITLE 
FROM JOBS J JOIN EMPLOYEES E
ON J.JOB_ID = E.JOB_ID AND UPPER(J.JOB_TITLE ) LIKE '%MANAGER%'
GROUP BY JOB_TITLE  ;

SELECT D.DNAME , LOC,E.ENAME 
FROM EMP E JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO AND E.ENAME LIKE '%L%';

/*
 *팀별 키가 가장큰 선수의 모든 정보 조회
 */
SELECT MAX(HEIGHT) ,TEAM_ID 
FROM PLAYER 
GROUP BY TEAM_ID ;


SELECT * FROM PLAYER p
INNER JOIN (SELECT MAX(HEIGHT) maxheight ,TEAM_ID 
FROM PLAYER 
GROUP BY TEAM_ID) m
ON p.TEAM_ID = m.TEAM_ID AND p.HEIGHT = m.maxheight
ORDER BY p.TEAM_ID , WEIGHT DESC ;


SELECT E.ENAME , E2.ENAME  FROM EMP E  JOIN EMP E2
ON E.MGR  = E2.EMPNO ;




