CREATE SEQUENCE SEQ_MEMBER2;

CREATE TABLE TBL_USER(
	USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR2 (500) NOT NULL,
	USER_NAME VARCHAR2 (500) NOT NULL,
	USER_PHONE VARCHAR2 (500) NOT NULL,
	USER_NICKNAME VARCHAR2(500),
	USER_EMAIL VARCHAR2 (500) NOT NULL ,
	USER_ADDRESS VARCHAR2 (500) ,
	USER_BIRTH DATE,
	USER_RECOMMENDER_ID VARCHAR2(500)
	);


SELECT * FROM TBL_USER ;


SELECT COUNT(USER_RECOMMENDER_ID) FROM TBL_USER 
GROUP BY USER_RECOMMENDER_ID 
HAVING USER_RECOMMENDER_ID = 'dmstkddlek12';







CREATE TABLE TBL_MEMBER2(
		NUM NUMBER PRIMARY KEY ,
		NAME VARCHAR2 (500),
		BIRTH_DATE DATE 
);

SELECT * FROM TBL_MEMBER2 ; 

INSERT INTO TBL_MEMBER2 
VALUES(4,'허은싱',TO_DATE('2000-01-03','YYYY-MM-DD'));