
--TBL_MEMBER 테이블 생성
CREATE TABLE TBL_MEMBER(
	NAME VARCHAR2(500),
	AGE NUMBER 
);

--자동차 테이블 생성
--제약 조건 : 테이블을 생성할 때 특정 컬럼에 조건을 부여하여 들어오는 데이터를 검사한다.
CREATE TABLE TBL_CAR(
	ID NUMBER,
	BRAND VARCHAR2(100),
	COLOR VARCHAR2(100),
	PRICE NUMBER,
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);
ALTER TABLE TBL_CAR RENAME TO TBL_SUPERCAR;

--제약 조건 삭제
ALTER TABLE TBL_CAR DROP CONSTRAINT CAR_PK;

--제약 조건 추가
ALTER  TABLE TBL_CAR ADD CONSTRAINT CAR_PK PRIMARY KEY(ID);
DROP TABLE TNL_ANIMAL ;
-------------------------------------------------------------------------------------
CREATE TABLE TBL_ANIMAL(
	ID NUMBER PRIMARY KEY,
	"TYPE" VARCHAR2(100),           --TYPE 은 오라클에서 어떠한 명령어이므로 명어를 컬럼며으로 사용하고 싶은경우 ""쌍따옴표로 감싼다.
	AGE NUMBER(3),
	FEED VARCHAR2(100)
);

ALTER TABLE TBL_ANIMAL DROP CONSTRAINT ANIMAL_PK;

ALTER TABLE TBL_ANIMAL ADD CONSTRAINT ANIMAL_PK PRIMARY KEY(ID);

SELECT * FROM TBL_CAR;
SELECT * FROM TBL_ANIMAL;
