UPDATE PLAYER
SET PLAYER_NAME = '허은상'
WHERE TEAM_ID ='K01';

SELECT * FROM PLAYER
WHERE TEAM_ID ='K01';

DELETE FROM PLAYER 
WHERE "POSITION" = 'MF';

SELECT * FROM PLAYER;

DELETE  FROM PLAYER 
WHERE HEIGHT >=180;

--AS(ALIAS) : 별칭
--SELECT 절 : AS뒤에 별칭 작성, 한칸 띄우고 작성
--FROM 절 : 한 칸 띄우고 작성

SELECT PLAYER_ID AS 선수번호 FROM PLAYER;
SELECT PLAYER_ID AS "선수 번호" FROM PLAYER;
SELECT PLAYER_ID "선수 번호" FROM PLAYER;

SELECT BACK_NO "등 번호", NVL(NICKNAME,'별명없음') "선수 별명"FROM PLAYER;

SELECT P.TEAM_ID "선수 테이블", T.TEAM_ID "팀 테이블" FROM PLAYER P,TEAM T;