SELECT * FROM PLAYER;
--ctrl a 는 전체선택

--PLAYER 테이블에서 TEAM_ID가 'K01' 인 선수 검색
SELECT * FROM PLAYER
WHERE TEAM_ID = 'K01';

SELECT * FROM PLAYER  WHERE TEAM_ID <>'K01';

SELECT * FROM PLAYER
WHERE WEIGHT BETWEEN 70 AND 80;

SELECT * FROM PLAYER 
WHERE TEAM_ID = 'K03' AND HEIGHT <180;


SELECT * FROM PLAYER 
WHERE  TEAM_ID ='K06' AND NICKNAME ='제리';

SELECT * FROM PLAYER 
WHERE HEIGHT >=170 AND WEIGHT >=80;

SELECT * FROM STADIUM
WHERE SEAT_COUNT >30000 AND SEAT_COUNT <=41000;

SELECT * FROM PLAYER 
WHERE TEAM_ID IN('K02','K07') AND "POSITION" = 'MF';