SELECT * FROM STADIUM;
SELECT * FROM TEAM;

SELECT T.TEAM_ID,  S.ADDRESS ,T.TEL  FROM STADIUM S,TEAM T;

--CONCATENATION(연결) : ||
--누구누구의 별명은 머머이다.

SELECT PLAYER_NAME, NICKNAME,PLAYER_NAME||'의 별명은' ||NICKNAME||'이다' FROM PLAYER;

SELECT E_PLAYER_NAME||'의 포지션은'||"POSITION"||'이다' 포지션 
FROM PLAYER;

--LIKE : 포함된 문자열의 값을 찾음, 문자의 개수도 제한을 줄 수 있음.
--% : 모든 것
--'%A' : A로 끝나는 모든 값 
--'_A' : A로 끝나면서 두자리인 값(AA),(BA),(PA)

SELECT * FROM TEAM
WHERE TEAM_NAME LIKE'%천마';

SELECT * FROM PLAYER WHERE PLAYER_NAME LIKE '김%';
SELECT * FROM PLAYER WHERE PLAYER_NAME LIKE '_김_';

SELECT * FROM PLAYER WHERE PLAYER_NAME LIKE '이%';
SELECT * FROM PLAYER WHERE PLAYER_NAME LIKE '%이%';

SELECT * FROM PLAYER WHERE PLAYER_NAME LIKE '김%' OR PLAYER_NAME LIKE '이%';

--이씨 아닌사람 찾기
--NOT : WHERE뒤에 바로쓰는것이 표준, LIKE전에써도 가능
SELECT * FROM PLAYER WHERE PLAYER_NAME NOT LIKE '이%';

SELECT * FROM PLAYER WHERE NOT PLAYER_NAME LIKE '김__';