--TBL_MEMBER 테이블 삭제
DROP TABLE TBL_MEMBER ;
--해당 영역 전체화면 : 클릭 후 CTRL + M
--주석 : 해석하지 못하게 하는 문법
--1. 쿼리문에 설명글을 달 때
--2.지금 당장 사용하지 않는 소스코드를 해석하고 싶지 않을 때

DROP TABLE TBL_CAR ;

--제약 조건 DEFAULT와 CHECK
--학생 테이블 생성
CREATE TABLE TBL_STUDENT(
	ID NUMBER,
	NAME VARCHAR2(100),
	MAJOR VARCHAR2(100),
	GENDER CHAR(1) DEFAULT 'W' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER IN('W','M')),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >=TO_DATE ('1980-01-01','YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)
);

INSERT INTO TBL_STUDENT
(ID, NAME, MAJOR, GENDER, BIRTH)
VALUES(1, '한동석', '컴퓨터공학과', 'M' , TO_DATE('1980-01-03','YYYY-MM-DD'));

SELECT * FROM TBL_STUDENT;

INSERT INTO TBL_STUDENT 
(ID,NAME,MAJOR,BIRTH)
VALUES(2,'홍길동','전자공학과',TO_DATE('2000-01-03','YYYY-MM-DD'));
INSERT INTO TBL_STUDENT 
(ID,MAJOR,BIRTH)
VALUES(3,'전자공학과',TO_DATE('2000-01-03','YYYY-MM-DD'));

TRUNCATE TABLE TBL_STUDENT ;
