CREATE TABLE FLOWER(
		FLOWERNAME VARCHAR2(200),
	COLOR VARCHAR2(100),
	PRICE NUMBER,
	CONSTRAINT FLOWER_PK PRIMARY KEY(FLOWERNAME)
);
SELECT  * FROM FLOWER;
CREATE TABLE POT(
 	POTID VARCHAR2(100),
 	POTCOLOR VARCHAR2(200),
 	POTSHAPE VARCHAR2(200),
 	FLOWERNAME VARCHAR2(200),
 	CONSTRAINT POT_PK PRIMARY KEY(POTID),
 	CONSTRAINT POT_FK FOREIGN KEY(FLOWERNAME) REFERENCES FLOWER(FLOWERNAME)
);

--펫과 주인
CREATE TABLE PET( 
	PETPIN VARCHAR2(100),
	PETAGE NUMBER,
	PETGENDER CHAR(1),
	PETTYPE VARCHAR2(100),
	CONSTRAINT PET_PK PRIMARY KEY(PETNAME)
);

CREATE TABLE OWNER(
	OWNERNAME VARCHAR2(100),
	OWNERAGE NUMBER,
	OWNERADDRESS VARCHAR2(100),
	OWNERPET VARCHAR2(100),
	CONSTRAINT OWNER_PK PRIMARY KEY(OWNERNAME),
	CONSTRAINT ONWER_FK FOREIGN KEY(OWNERPET) REFERENCES PET(PETNAME)
);