SELECT * FROM EMP;

SELECT D.LOC 
FROM EMP E INNER JOIN DEPT d
ON E.DEPTNO  = D.DEPTNO ;

SELECT *FROM EMP;
SELECT *FROM DEPT;

SELECT T.TEL 
FROM PLAYER p JOIN TEAM t 
ON P.TEAM_ID  = T.TEAM_ID AND P.PLAYER_NAME ='송종국';

SELECT E.EMAIL , E.FIRST_NAME , E.LAST_NAME ,J.JOB_TITLE 
FROM JOBS J JOIN EMPLOYEES E 
ON J.JOB_ID = E.JOB_ID ;

SELECT *
FROM EMP e INNER JOIN SALGRADE s 
ON (E.SAL BETWEEN S.LOSAL  AND S.HISAL)
JOIN DEPT D 
ON D.DEPTNO =E.DEPTNO ;

SELECT * 
FROM EMP E, SALGRADE s , DEPT d 
WHERE E.SAL  BETWEEN S.LOSAL AND S.HISAL AND D.DEPTNO = E.DEPTNO ;


SELECT FIRST_NAME,HIRE_DATE,DEPARTMENT_NAME 
FROM EMPLOYEES e JOIN DEPARTMENTS d 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.HIRE_DATE BETWEEN '20030101' AND '20060101';

--네츄럴 조인
SELECT * FROM EMP E INNER JOIN DEPT D 
USING(DEPTNO);

SELECT * FROM EMP E NATURAL JOIN DEPT D


--외부 조인
SELECT * FROM STADIUM;
SELECT * FROM TEAM;

SELECT * 
FROM STADIUM s LEFT OUTER JOIN TEAM t 
ON S.HOMETEAM_ID = T.TEAM_ID ;

--SLEF JOIN
SELECT * FROM EMP;

SELECT E.ENAME , E2.ENAME
FROM EMP e JOIN EMP e2 
ON E.MGR = E2.EMPNO ;

