CREATE TABLE SCHOOL(
	STUDENT_ID NUMBER(10),
	STUDENT_NAME VARCHAR2(100),
	STUDENT_MAJOR VARCHAR2(100),
	STUDENT_AGE NUMBER(3),
	STUDENT_GENDER CHAR(1)
);

SELECT * FROM SCHOOL;

ALTER TABLE SCHOOL 
	ADD (STDUENT_ADDRESS VARCHAR2(100));
	
ALTER TABLE SCHOOL ADD(PHONE_NUMBER VARCHAR2(200) NOT NULL UNIQUE);

--제약 조건 추가

ALTER TABLE SCHOOL ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_ID);

--컬럼 속성 수정
ALTER TABLE SCHOOL MODIFY(STUDENT_GENDER NUMBER(1) DEFAULT 0 NOT NULL);

--컬럼 삭제
ALTER TABLE SCHOOL DROP COLUMN STUDENT_AGE;

--제약조건 삭제
ALTER TABLE SCHOOL DROP CONSTRAINT SYS_C007126;

--컬럼이름 변경
ALTER TABLE SCHOOL RENAME COLUMN PHONE_NUMBER TO STUDENT_PHONE;
--제약조건 이름 변경
ALTER TABLE SCHOOL RENAME CONSTRAINT STUDENT_PK TO PK_STUDNET;
--테이블 이름 변경
ALTER TABLE SCHOOL RENAME TO UNIVERSITY;
--제약조건 활성화 비활성화
ALTER TABLE UNIVERSITY ENABLE CONSTRAINT PK_STUDNET;

INSERT INTO UNIVERSITY 
VALUES(1,'김철수', '경영', 0, '서울시','01042322312');

INSERT INTO UNIVERSITY 
VALUES(2,'김철이', '컴퓨터', 5, '서울시','01042342312');
INSERT INTO UNIVERSITY 
VALUES(3,'김철지', '경영', 0, '서울시','01042352312');
INSERT INTO UNIVERSITY 
VALUES(4,'김철디', '경영', 0, '서울시','01042372312');

SELECT * FROM UNIVERSITY;
TRUNCATE TABLE UNIVERSITY ;

DELETE UNIVERSITY
WHERE STUDENT_ID = 2;

DROP TABLE UNIVERSITY ;



GRANT SELECT, UPDATE ON EMPLOYEES TO GUEST;

SELECT * FROM USER_TAB_PRIVS_MADE;

REVOKE SELECT ON EMPLOYEES FROM GUEST;