SELECT * FROM TBL_USER tu ORDER BY id DESC ;

SELECT * FROM TBL_NOTICE tn ;

ALTER TABLE TBL_USER  ADD USER_INTRODUCING_MESSAGE VARCHAR2(500);
SELECT * FROM TBL_PLOGGING tp ;

INSERT INTO HR.TBL_PLOGGING_REVIEW
(ID, USER_ID, PLOGGING_ID, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_REGISTER_DATE, REVIEW_UPDATED_DATE)
VALUES(23, 84, 1, '즐거운 플로깅', '테스트 내용1', TIMESTAMP '2023-05-20 05:13:55.000000', TIMESTAMP '2023-05-20 05:13:55.000000');
INSERT INTO HR.TBL_PLOGGING_REVIEW
(ID, USER_ID, PLOGGING_ID, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_REGISTER_DATE, REVIEW_UPDATED_DATE)
VALUES(24, 84, 2, '함께지키는 우리', '테스트 내용2', TIMESTAMP '2023-05-20 05:19:36.000000', TIMESTAMP '2023-05-20 05:19:36.000000');

INSERT INTO HR.TBL_REVIEW_IMAGE
(ID, PLOGGING_REVIEW_ID, REVIEW_IMAGE_IMAGE_NAME, REVIEW_IMAGE_IMAGE_UUID, REVIEW_IMAGE_IMAGE_SIZE, REVIEW_IMAGE_PATH, REVIEW_IMAGE_TYPE)
VALUES(3, 23, '김인진짱.png', '0d8a7b45-0c4f-4e40-bf34-f8dbd6157e0c', 1231231, '2023/05/18', 'REPRESENTATIVE');
INSERT INTO HR.TBL_REVIEW_IMAGE
(ID, PLOGGING_REVIEW_ID, REVIEW_IMAGE_IMAGE_NAME, REVIEW	_IMAGE_IMAGE_UUID, REVIEW_IMAGE_IMAGE_SIZE, REVIEW_IMAGE_PATH, REVIEW_IMAGE_TYPE)
VALUES(2, 24, '문우람짱.png', '48bc88c1-942f-471e-beb3-90aafc855543', 1231231, '2023/05/18', 'REPRESENTATIVE');

SELECT * FROM TBL_PLOGGING tp  ;

SELECT * FROM TBL_FOLLOW tf ;

 INSERT INTO TBL_FOLLOW
(ID, FOLLOWER_ID, FOLLOWING_ID, FOLLOW_START_DATE)
VALUES(SEQ_FOLLOW.NEXTVAL, 26,84 , SYSDATE);

INSERT INTO TBL_PARTICIPANT
(ID, USER_ID, PLOGGING_ID)
VALUES(SEQ_PARTICIPANT.NEXTVAL,84 ,3 );

SELECT * FROM TBL_USER tu ;

SELECT *FROM TBL_PLOGGING_REVIEW tpr ;



INSERT INTO TBL_PARTICIPANT
(ID, USER_ID, PLOGGING_ID)
VALUES(SEQ_PARTICIPANT.NEXTVAL,84 ,2 );

SELECT * FROM TBL_PRODUCT tp ORDER BY id DESC ;

SELECT * FROM TBL_PRODUCT_WISH tpw ;

INSERT  INTO TBL_PRODUCT_WISH 
values(SEQ_PRODUCT_WISH.NEXTVAL,32,110);

SELECT * FROM TBL_COUPON tc ;

SELECT *FROM TBL_TISSUE tt ;

INSERT INTO TBL_TISSUE
(ID, USER_ID, TISSUE_CREATED_DATE, TISSUE_POINT, TISSUE_HISTORY)
VALUES(SEQ_TISSUE.NEXTVAL, 84, SYSDATE, 10, '부산 해운대 플로깅 참여 리뷰 작성 보상');


INSERT INTO TBL_PRODUCT
(ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION, PRODUCT_IMAGE_NAME, PRODUCT_IMAGE_UUID, PRODUCT_IMAGE_SIZE, PRODUCT_IMAGE_PATH)
VALUES(32, '1dsazsdf', 'ㅁ', 5, 5, SYSDATE, SYSDATE, ('전체') , ('전체') , '', '', 0, '');


INSERT INTO HR.TBL_PLOGGING
(ID, LOCAL_CREATOR_ID, PLOGGING_TITLE, PLOGGING_CONTENT, PLOGGING_START_LOCATION, PLOGGING_END_LOCATION, PLOGGING_ESTIMATED_TIME, PLOGGING_MAXIMUM_PARTICIPANT, PLOGGING_START_DATETIME, PLOGGING_STATUS, PLOGGING_APPLY_DATE, PLOGGING_REJECTED_REASON, PLOGGING_REGISTER_DATE, PLOGGING_UPDATED_DATE, PLOGGING_VIEWED_COUNT, PLOGGING_IMAGE_NAME, PLOGGING_IMAGE_UUID, PLOGGING_IMAGE_SIZE)
VALUES( SEQ_PLOGGING.NEXTVAL  , 84, '경주 벚꽃축제 플로깅', '내용', '경상북도 경주시 계림로', '경상북도 경주시 계림로', 0, 0, '2023-3-31', ('estimating') , SYSDATE, 'reason', SYSDATE, SYSDATE, (0) , '', '', 0)

(SEQ_PLOGGING.NEXTVAL  , 84, '청주시 육거리시장 플로깅', '내용', '충청북도 청주시 상당구', '충청북도 청주시 상당구', 0, 0, '2023-05-23', ('estimating') , SYSDATE, 'reason', SYSDATE, SYSDATE, (0) , '', '', 0)




( SEQ_PLOGGING.NEXTVAL  , 84,'제주 서귀포 해안가 플로깅', '내용', '제주도 서귀포시 보목포로', '제주도 서귀포시 보목포로', 0, 0, '2023-07-18', ('estimating') , SYSDATE, 'reason', SYSDATE, SYSDATE, (0) , '', '', 0)



INSERT INTO TBL_NOTICE
(ID, ADMIN_ID, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATED_DATE, NOTICE_UPDATED_DATE, NOTICE_VIEWED_COUNT, NOTICE_IMAGE_NAME, NOTICE_IMAGE_UUID, NOTICE_IMAGE_SIZE)
VALUES(SEQ_NOTICE.NEXTVAL, 81, '플로깅에 대하여', '플로깅은 이삭을 줍는다(plocka upp)는 뜻의 스웨던어와 영어 조깅(jogging)의 합성어로 산책이나 조깅 등 운동을 하며 쓰레기를 줍는 전세계적 환경운동의 하나다.
이번 플로깅 캠페인은 바이엘의 사회 참여 활동(Corporate Social Engagement) 중 하나인 ̒글뤽 포 그린 캠페인(Glück for Green)의 일환으로 개최된다.
올해 글뤽 포 그린 플로깅 캠페인은 이벤트성으로  해와 달리,1회 이상'
, SYSDATE, SYSDATE, (0) , 'plog', 'asd',1);

