CREATE SEQUENCE SEQ_NOTICE;

-- HR.TBL_NOTICE definition

CREATE TABLE "TBL_NOTICE" 
   (	"ID" NUMBER, 
	"ADMIN_ID" NUMBER NOT NULL ENABLE, 
	"NOTICE_TITLE" VARCHAR2(500) NOT NULL ENABLE, 
	"NOTICE_CONTENT" VARCHAR2(500) NOT NULL ENABLE, 
	"NOTICE_CREATED_DATE" DATE DEFAULT SYSDATE, 
	"NOTICE_UPDATED_DATE" DATE DEFAULT SYSDATE, 
	"NOTICE_VIEWED_COUNT" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"NOTICE_IMAGE_NAME" VARCHAR2(500), 
	"NOTICE_IMAGE_UUID" VARCHAR2(500), 
	"NOTICE_IMAGE_SIZE" NUMBER, 
	 CONSTRAINT "PK_NOTICE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_NOTICE_USER" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "TBL_USER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_NOTICE" ON "TBL_NOTICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;