CREATE SEQUENCE SEQ_PARTICIPANT;

-- HR.TBL_PARTICIPANT definition

CREATE TABLE "TBL_PARTICIPANT" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PLOGGING_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_PARTICIPANT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PARTICIPANT_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "TBL_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_PARTICIPANT_PLOGGING" FOREIGN KEY ("PLOGGING_ID")
	  REFERENCES "TBL_PLOGGING" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_PARTICIPANT" ON "TBL_PARTICIPANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;