CREATE SEQUENCE SEQ_PLOGGING;

-- HR.TBL_PLOGGING definition

CREATE TABLE "TBL_PLOGGING" 
   (	"ID" NUMBER, 
	"LOCAL_CREATOR_ID" NUMBER NOT NULL ENABLE, 
	"PLOGGING_TITLE" VARCHAR2(500) NOT NULL ENABLE, 
	"PLOGGING_CONTENT" VARCHAR2(500) NOT NULL ENABLE, 
	"PLOGGING_START_LOCATION" VARCHAR2(500) NOT NULL ENABLE, 
	"PLOGGING_END_LOCATION" VARCHAR2(500) NOT NULL ENABLE, 
	"PLOGGING_ESTIMATED_TIME" NUMBER NOT NULL ENABLE, 
	"PLOGGING_MAXIMUM_PARTICIPANT" NUMBER NOT NULL ENABLE, 
	"PLOGGING_START_DATETIME" DATE NOT NULL ENABLE, 
	"PLOGGING_STATUS" VARCHAR2(500) DEFAULT ('estimating') NOT NULL ENABLE, 
	"PLOGGING_APPLY_DATE" DATE DEFAULT SYSDATE, 
	"PLOGGING_REJECTED_REASON" VARCHAR2(500), 
	"PLOGGING_REGISTER_DATE" DATE, 
	"PLOGGING_UPDATED_DATE" DATE, 
	"PLOGGING_VIEWED_COUNT" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"PLOGGING_IMAGE_NAME" VARCHAR2(500), 
	"PLOGGING_IMAGE_UUID" VARCHAR2(500), 
	"PLOGGING_IMAGE_SIZE" NUMBER, 
	 CONSTRAINT "PK_PLOGGING" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PLOGGING_USER" FOREIGN KEY ("LOCAL_CREATOR_ID")
	  REFERENCES "TBL_USER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_PLOGGING" ON "TBL_PLOGGING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;