CREATE SEQUENCE SEQ_PRODUCT_WISH;

-- HR.TBL_PRODUCT_WISH definition

CREATE TABLE "TBL_PRODUCT_WISH" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRODUCT_WISH" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PRODUCT_WISH_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "TBL_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_WISH_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "TBL_PRODUCT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_PRODUCT_WISH" ON "TBL_PRODUCT_WISH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 INSERT INTO TBL_PRODUCT_WISH
(ID, USER_ID, PRODUCT_ID)
VALUES(SEQ_PRODUCT_WISH.NEXTVAL, 32, 27);

SELECT * FROM TBL_PRODUCT_WISH tpw ORDER BY id DESC ;

SELECT ROWNUM R, PRODUCT_NAME  FROM 
(SELECT PRODUCT_NAME  FROM TBL_PRODUCT tp ORDER BY PRODUCT_COST )
WHERE 


--상품리스트 뿌릴때 쿼리 정렬, 검색 페이징 
SELECT  R ,TP.ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION, PRODUCT_IMAGE_NAME, PRODUCT_IMAGE_UUID, PRODUCT_IMAGE_SIZE,USER_WISH_COUNT
	FROM (
SELECT ROWNUM R ,TP.ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION, PRODUCT_IMAGE_NAME, PRODUCT_IMAGE_UUID, PRODUCT_IMAGE_SIZE,USER_WISH_COUNT
		FROM 
		(
		SELECT TP.ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION, PRODUCT_IMAGE_NAME, PRODUCT_IMAGE_UUID, PRODUCT_IMAGE_SIZE,COUNT(USER_ID) USER_WISH_COUNT
		FROM TBL_PRODUCT TP LEFT OUTER JOIN TBL_PRODUCT_WISH TPW 
		ON TP.ID = TPW.PRODUCT_ID
		GROUP BY TP.ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION, PRODUCT_IMAGE_NAME, PRODUCT_IMAGE_UUID, PRODUCT_IMAGE_SIZE
		--최신순
			ORDER BY ID DESC
		--인기순
		/*ORDER BY  USER_WISH_COUNT DESC*/
		) TP
		--카테고리
		WHERE TP.PRODUCT_CATEGORY ='음료' 
		--사용장소
		AND TP.PRODUCT_USED_LOCATION LIKE '%가평%'
	)TP 
	--페이징처리
	WHERE R>=1 AND R<8;

	SELECT PRODUCT_ID FROM  TBL_PRODUCT_WISH tpw 
	WHERE USER_ID =40;

	   SELECT PRODUCT_ID FROM  TBL_PRODUCT_WISH tpw
        WHERE USER_ID =30;
        

