CREATE SEQUENCE SEQ_PRODUCT;

SELECT PRODUCT_IMAGE_PATH FROM TBL_PRODUCT tp ;		
ALTER TABLE TBL_PRODUCT ADD PRODUCT_IMAGE_PATH VARCHAR2 (500);

CREATE TABLE "TBL_PRODUCT" 
   (	"ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(1000) NOT NULL ENABLE, 
	"PRODUCT_DETAIL" VARCHAR2(1000) NOT NULL ENABLE, 
	"PRODUCT_COST" NUMBER NOT NULL ENABLE, 
	"PRODUCT_STOCK" NUMBER NOT NULL ENABLE, 
	"PRODUCT_REGISTER_DATE" DATE DEFAULT SYSDATE, 
	"PRODUCT_UPDATED_DATE" DATE DEFAULT SYSDATE, 
	"PRODUCT_CATEGORY" VARCHAR2(500) DEFAULT ('전체') NOT NULL ENABLE, 
	"PRODUCT_USED_LOCATION" VARCHAR2(500) DEFAULT ('전체') NOT NULL ENABLE, 
	"PRODUCT_IMAGE_NAME" VARCHAR2(500), 
	"PRODUCT_IMAGE_UUID" VARCHAR2(500), 
	"PRODUCT_IMAGE_SIZE" NUMBER, 
	 CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("PRODUCT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_PRODUCT" ON "TBL_PRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "SYS_C008062" ON "TBL_PRODUCT" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
 INSERT INTO TBL_PRODUCT
(ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION)
VALUES(SEQ_PRODUCT.NEXTVAL, '에슬로우 커피 원액 500ml', '에슬로우에서만 맛 볼 수 있는 특별한 초콜릿향 커피 원액', 3, 20, SYSDATE, SYSDATE, ('음료') , ('서울특별시 역삼동 전지역 에슬로우 카페'));


SELECT * FROM TBL_PRODUCT tp ORDER BY id desc ; 
SELECT * FROM TBL_USER tu ;
SELECT * FROM TBL_COUPON ;

 SELECT * FROM TBL_PRODUCT_WISH tpw ;
 SELECT * FROM TBL_PRODUCT tp ;
 

SELECT TP.ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION, PRODUCT_IMAGE_NAME, PRODUCT_IMAGE_UUID, PRODUCT_IMAGE_SIZE,PRODUCT_IMAGE_PATH,COUNT(USER_ID) USER_WISH_COUNT
        FROM TBL_PRODUCT TP  LEFT OUTER JOIN TBL_PRODUCT_WISH TPW
        ON TP.ID = TPW.PRODUCT_ID
        WHERE tp.id=95
        GROUP BY TP.ID, PRODUCT_NAME, PRODUCT_DETAIL, PRODUCT_COST, PRODUCT_STOCK, PRODUCT_REGISTER_DATE, PRODUCT_UPDATED_DATE, PRODUCT_CATEGORY, PRODUCT_USED_LOCATION, PRODUCT_IMAGE_NAME, PRODUCT_IMAGE_UUID, PRODUCT_IMAGE_SIZE,PRODUCT_IMAGE_PATH