CREATE SEQUENCE SEQ_REVIEW_IMAGE;

-- HR.TBL_REVIEW_IMAGE definition

ALTER TABLE TBL_REVIEW_IMAGE ADD REVIEW_IMAGE_TYPE 	 VARCHAR2 (500);

CREATE TABLE "TBL_REVIEW_IMAGE" 
   (	"ID" NUMBER, 
	"PLOGGING_REVIEW_ID" NUMBER NOT NULL ENABLE, 
	"REVIEW_IMAGE_IMAGE_NAME" VARCHAR2(500), 
	"REVIEW_IMAGE_IMAGE_UUID" VARCHAR2(500), 
	"REVIEW_IMAGE_IMAGE_SIZE" NUMBER, 
	 CONSTRAINT "PK_REVIEW_IMAGE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_REVIEW_IMAGE_REVIEW" FOREIGN KEY ("PLOGGING_REVIEW_ID")
	  REFERENCES "TBL_PLOGGING_REVIEW" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_REVIEW_IMAGE" ON "TBL_REVIEW_IMAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 
 SELECT * FROM TBL_REVIEW_IMAGE tri ;