CREATE SEQUENCE SEQ_REVIEW_REPLY;

-- HR.TBL_REVIEW_REPLY definition

CREATE TABLE "TBL_REVIEW_REPLY" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PLOGGING_REVIEW_ID" NUMBER NOT NULL ENABLE, 
	"REPLY_CONTENT" VARCHAR2(500) NOT NULL ENABLE, 
	"REPLY_REGISTER_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"REPLY_UPDATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_REVIEW_REPLY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_REVIEW_REPLY_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "TBL_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_REPLY_REVIEW" FOREIGN KEY ("PLOGGING_REVIEW_ID")
	  REFERENCES "TBL_PLOGGING_REVIEW" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_REVIEW_REPLY" ON "TBL_REVIEW_REPLY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;